# Legt den Filter-Proxy in den Windows-Autostart (Benutzer-Anmeldung).
# - Startup-Ordner: VBS ohne sichtbares Fenster
# - Optional: geplante Aufgabe (zuverlaessiger)
#
# Aufruf:
#   powershell -ExecutionPolicy Bypass -File scripts\install_autostart.ps1
#   powershell -ExecutionPolicy Bypass -File scripts\install_autostart.ps1 -ScheduledTask
#   powershell -ExecutionPolicy Bypass -File scripts\install_autostart.ps1 -Remove

param(
    [switch]$ScheduledTask,
    [switch]$Remove
)

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$GrokHome = Join-Path $env:USERPROFILE ".grok"
$ProxyDir = Join-Path $GrokHome "proxy"
$Startup = [Environment]::GetFolderPath("Startup")
$VbsName = "GrokPrivacyFilterProxy.vbs"
$VbsStartup = Join-Path $Startup $VbsName
$TaskName = "GrokPrivacyFilterProxy"

# ensure_proxy + proxy script nach ~/.grok kopieren
New-Item -ItemType Directory -Force -Path $ProxyDir | Out-Null
New-Item -ItemType Directory -Force -Path (Join-Path $ProxyDir "logs") | Out-Null
Copy-Item -Force (Join-Path $RepoRoot "proxy\xai_filter_proxy.py") (Join-Path $ProxyDir "xai_filter_proxy.py")
Copy-Item -Force (Join-Path $RepoRoot "scripts\ensure_proxy.py") (Join-Path $ProxyDir "ensure_proxy.py")

$EnsurePy = Join-Path $ProxyDir "ensure_proxy.py"
$VbsBody = @"
' Auto-generated by grok-privacy-filter install_autostart.ps1
Set sh = CreateObject("WScript.Shell")
py = "py"
' ensure_proxy startet nur wenn Port frei
sh.Run "py -3 ""$EnsurePy""", 0, False
"@

if ($Remove) {
    if (Test-Path $VbsStartup) {
        Remove-Item -Force $VbsStartup
        Write-Host "Entfernt: $VbsStartup"
    }
    $existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($existing) {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
        Write-Host "Geplante Aufgabe entfernt: $TaskName"
    }
    Write-Host "Autostart entfernt."
    exit 0
}

# Startup-Ordner (immer)
Set-Content -Path $VbsStartup -Value $VbsBody -Encoding ASCII
Write-Host "Autostart (Startup-Ordner): $VbsStartup" -ForegroundColor Green

if ($ScheduledTask) {
    $action = New-ScheduledTaskAction -Execute "py" -Argument "-3 `"$EnsurePy`""
    $trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
    $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable
    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings -Force | Out-Null
    Write-Host "Geplante Aufgabe: $TaskName (AtLogOn)" -ForegroundColor Green
}

# Sofort sicherstellen
& py -3 $EnsurePy
if ($LASTEXITCODE -ne 0) {
    Write-Warning "ensure_proxy meldete Fehler (Exit $LASTEXITCODE). Logs: $ProxyDir\logs\"
} else {
    Write-Host "Proxy laeuft bzw. wurde gestartet." -ForegroundColor Green
}

Write-Host ""
Write-Host "Hinweis: Nach Login startet der Proxy unsichtbar."
Write-Host "Entfernen:  install_autostart.ps1 -Remove"
