# Autostart with absolute Python path
#   install_autostart.ps1
#   install_autostart.ps1 -ScheduledTask
#   install_autostart.ps1 -Watchdog
#   install_autostart.ps1 -Remove

param(
    [switch]$ScheduledTask,
    [switch]$Watchdog,
    [switch]$Remove
)

$ErrorActionPreference = "Stop"
$RepoRoot = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$ProxyDir = Join-Path $env:USERPROFILE ".grok\proxy"
$Startup = [Environment]::GetFolderPath("Startup")
$VbsStartup = Join-Path $Startup "GrokPrivacyFilterProxy.vbs"
$TaskName = "GrokPrivacyFilterProxy"
$WatchdogName = "GrokPrivacyFilterWatchdog"

New-Item -ItemType Directory -Force -Path (Join-Path $ProxyDir "logs") | Out-Null
Copy-Item -Force (Join-Path $RepoRoot "proxy\xai_filter_proxy.py") (Join-Path $ProxyDir "xai_filter_proxy.py")
Copy-Item -Force (Join-Path $RepoRoot "proxy\policy.json") (Join-Path $ProxyDir "policy.json")
Copy-Item -Force (Join-Path $RepoRoot "scripts\ensure_proxy.py") (Join-Path $ProxyDir "ensure_proxy.py")

$PyExe = $null
try { $PyExe = (& py -3 -c "import sys; print(sys.executable)").Trim() } catch {}
if (-not $PyExe) {
    try { $PyExe = (& python -c "import sys; print(sys.executable)").Trim() } catch {}
}
if (-not $PyExe -or -not (Test-Path $PyExe)) {
    throw "Python 3 not found (py -3 / python)."
}

$EnsurePy = Join-Path $ProxyDir "ensure_proxy.py"
Write-Host "Python: $PyExe"
Write-Host "ensure: $EnsurePy"

if ($Remove) {
    if (Test-Path $VbsStartup) {
        Remove-Item -Force $VbsStartup
        Write-Host "Removed Startup VBS"
    }
    foreach ($n in @($TaskName, $WatchdogName)) {
        $t = Get-ScheduledTask -TaskName $n -ErrorAction SilentlyContinue
        if ($t) {
            Unregister-ScheduledTask -TaskName $n -Confirm:$false
            Write-Host "Removed task $n"
        }
    }
    Write-Host "Autostart removed."
    exit 0
}

$VbsBody = @"
' Auto-generated by grok-privacy-filter install_autostart.ps1
Set sh = CreateObject("WScript.Shell")
sh.Run """$PyExe"" ""$EnsurePy""", 0, False
"@
Set-Content -Path $VbsStartup -Value $VbsBody -Encoding ASCII
Write-Host "Startup VBS: $VbsStartup" -ForegroundColor Green

if ($ScheduledTask -or $Watchdog) {
    $action = New-ScheduledTaskAction -Execute $PyExe -Argument "`"$EnsurePy`""
    $trigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
    $settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable
    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings -Force | Out-Null
    Write-Host "Scheduled task: $TaskName" -ForegroundColor Green
}

if ($Watchdog) {
    $wAction = New-ScheduledTaskAction -Execute $PyExe -Argument "`"$EnsurePy`" --watchdog --interval-secs 90"
    $wTrigger = New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
    $wSettings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -StartWhenAvailable
    Register-ScheduledTask -TaskName $WatchdogName -Action $wAction -Trigger $wTrigger -Settings $wSettings -Force | Out-Null
    Write-Host "Watchdog task: $WatchdogName" -ForegroundColor Green
}

& $PyExe $EnsurePy -v
if ($LASTEXITCODE -ne 0) {
    Write-Warning "ensure_proxy exit $LASTEXITCODE - see $ProxyDir\logs"
} else {
    Write-Host "Proxy OK" -ForegroundColor Green
}
